### ISSUE TITLE
试用了Demo感觉很好用

### ISSUE THREAD

**Issue by guoai2015** [jkkj93/FREYA-STREAM-CASTER-SDK-FOR-ANDROID#1]
试用了一下例子APK，做的很炫，延迟也很低，非常好。就是代码中注释很少，小弟刚开始研究直播，问一下作者可否留下联系方式以供交流？

**Comment by jkkj93** [comment]
感谢支持，下一次更新时我会增加详细注释，请留下QQ号，我来加你。

**Comment by guoai2015** [comment]
感谢作者及时反馈，我的QQ号是497918526

**Comment by jkkj93** [comment]
已加QQ

**Comment by hkercn** [comment]
你好，我的QQ：2510934398，在研究你的demo和sdk，希望能够加Q交流

**Comment by jkkj93** [comment]
已加楼上QQ
