### ISSUE TITLE
GOP参数和Frame rate 有什么关系吗

### ISSUE THREAD

**Issue by gordonpro** [jkkj93/FREYA-STREAM-CASTER-SDK-FOR-ANDROID#2]
Demo中默认是2FRAMES和5FRAMES. 

这个是不是对应一般其他encoder的 setFrameRate(2) setFrameRate(5) ?

**Comment by jkkj93** [comment]
GOP参数与帧率无关，设置较小的GOP参数可以获得更高的视频质量
如果需要调节帧率参数，可以修改FreyaCameraVideoProcessor->initCamera中setPreviewFpsRange函数的参数及其上层的条件语句，在摄像头支持的范围内设置帧率。
